# Generated by Django 4.1.2 on 2022-10-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='player1_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='player2_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
