# Generated by Django 4.1.2 on 2022-10-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_player1_count_question_player2_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='player1',
            new_name='player1_name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='player2',
            new_name='player2_name',
        ),
    ]
